<?xml version="1.0" encoding="UTF-8"?>
<!--+
    |
    | <meta:header>
    |   <meta:licence>
    |     Copyright (C) 2026 University of Manchester.
    |
    |     This information is free software: you can redistribute it and/or modify
    |     it under the terms of the GNU General Public License as published by
    |     the Free Software Foundation, either version 3 of the License, or
    |     (at your option) any later version.
    |
    |     This information is distributed in the hope that it will be useful,
    |     but WITHOUT ANY WARRANTY; without even the implied warranty of
    |     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    |     GNU General Public License for more details.
    |
    |     You should have received a copy of the GNU General Public License
    |     along with this program.  If not, see <http://www.gnu.org/licenses/>.
    |   </meta:licence>
    | </meta:header>
    |
    | AIMetrics: [
    |     {
    |     "timestamp": "2026-05-30T06:03:00",
    |     "name": "Cursor CLI",
    |     "version": "2026.02.13-41ac335",
    |     "model": "Claude 4.6 Opus (Thinking)",
    |     "contribution": {
    |       "value": 5,
    |       "units": "%"
    |       }
    |     }
    |   ]
    |
    +-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>net.ivoa.calycopis</groupId>
	<artifactId>calycopis-broker</artifactId>
	<version>1.0.6-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>Calycopis broker webapp</name>
	<description>IVOA ExecutionBroker Spring Boot implementation</description>

	<properties>
		<java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <!--+
            | Enable annotation processing in the compiler.
            | https://stackoverflow.com/a/79367717
            | https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#proc
            | Starting with JDK 21, this option must be set explicitly.
            +-->
        <maven.compiler.proc>full</maven.compiler.proc>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

    <repositories>
        <!--+
            | This requires a personal access token with package:read
            | permissions in the user's ~/m2/settings.xml file.
            | https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#installing-a-package
            | https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages
            +-->
        <repository>
            <id>github-ivoa</id>
            <name>IVOA packages on GitHub</name>
            <url>https://maven.pkg.github.com/ivoa/*</url>
            <snapshots>
              <enabled>true</enabled>
            </snapshots>
        </repository>
        <!--+
            | This embeds a personal access token with package:read
            | permissions in the repository URL.
            | https://github.com/orgs/community/discussions/25629#discussioncomment-3248525
            | If we want to do this, we should create a separate machine
            | account with read-only access to IVOA projects.
            | https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#machine-users
        <repository>
            <id>github-public</id>
            <url>https://public:&#103;####################@maven.pkg.github.com/ivoa/*</url>
            <snapshots>
              <enabled>true</enabled>
            </snapshots>
        </repository>
            +-->
    </repositories>

	<dependencies>
        <!--+
            | Include the Spring Boot classes generated from the schema.
            | https://github.com/Zarquan/Calycopis-schema
            +-->
        <dependency>
            <groupId>net.ivoa.calycopis</groupId>
            <artifactId>calycopis-schema-spring</artifactId>
            <version>1.0.6-SNAPSHOT</version>
        </dependency>

        <!--+
            | Include our generated Skaha client.
        <dependency>
            <groupId>net.ivoa.calycopis</groupId>
            <artifactId>skaha-client</artifactId>
        	<version>0.1-SNAPSHOT</version>
        </dependency>
            +-->

        <!--+
            | GitHub UUID generator.
            +-->
        <dependency>
          <groupId>com.github.f4b6a3</groupId>
          <artifactId>uuid-creator</artifactId>
          <version>6.1.1</version>
        </dependency>

        <!--+
            | Embedded H2 database.
            | https://www.baeldung.com/spring-boot-h2-database
            +-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!--+
            | ThreeTen time classes.
            | https://github.com/ThreeTen/threeten-extra
            +-->
        <dependency>
          <groupId>org.threeten</groupId>
          <artifactId>threeten-extra</artifactId>
          <version>1.8.0</version>
        </dependency>

        <!--+
            | Add slf4j and log4j logging.
            | https://www.baeldung.com/java-logging-intro
            | (versions are managed by SpringBoot)
            +-->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>

        <!--+
            | Exclude default logging from SpringBoot.
            | https://stackoverflow.com/a/61873064
            +-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>

        <!--+
            | Project Lombok
            | https://projectlombok.org/
            +-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <!--version>${lombok.version}</version-->
            <scope>provided</scope>
        </dependency>

        <!--+
            | Java Servlet
            | https://stackoverflow.com/a/76034931
            +-->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>1.14.0</version>
        </dependency>

    	<dependency>
        	<groupId>wtf.metio.storage-units</groupId>
        	<artifactId>storage-units-model</artifactId>
        	<version>2025.8.6</version>
    	</dependency>

        <!--+
            | Spring Security and OAuth2 Resource Server.
            | (versions are managed by SpringBoot)
            +-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>

        <!--+
            | Spring dependencies.
            | (versions are managed by SpringBoot)
            +-->
        <dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

        <!--+
            | Jackson annotations.
            | (versions are managed by SpringBoot)
            +-->
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <!--+
            | Added springdoc-openapi to generate OpenAPI spec.
            | https://stackoverflow.com/questions/55938207/how-to-generate-openapi-3-0-spec-from-existing-spring-boot-app
            | https://www.baeldung.com/spring-rest-openapi-documentation
            | Fails due to an incompatible version issue.
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.9</version>
        </dependency>
            +-->

        <!--+
            | PostgreSQL JDBC driver
            +-->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.8</version>
        </dependency>

        <!--+
            | Docker Java client library.
            | https://github.com/docker-java/docker-java
            +-->
        <dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java-core</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java-transport-zerodep</artifactId>
            <version>3.4.1</version>
        </dependency>

	</dependencies>

	<build>

		<plugins>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

		</plugins>
	</build>

</project>
