#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2026, University of Manchester (http://www.manchester.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this software. If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#zrq-notes-indent
#
# AIMetrics: []
#

version: '3'

networks:

    calycopis:
        name: calycopis-network
        external: true

services:

    broker:
        image: "localhost/calycopis/calycopis-broker"
        networks:
            - calycopis
        ports:
            - "8082:8082"

    postgresql:
        image: "docker.io/library/postgres:latest"
        networks:
            - calycopis
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: calycopis
            POSTGRES_USER: albert
            POSTGRES_PASSWORD: UVai0wie-wa9Eed4g

    client:
        image: "ghcr.io/ivoa/calycopis/developer-tools:latest"
        # https://stackoverflow.com/a/39150040
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        networks:
            - calycopis



